version: '3.3'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:latest
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./local_cert/:/etc/certs/
      - ./traefik_virt.yml:/traefik.yml:ro

# Add the catapp service
  catapp:
     image: mikesir87/cats:1.0
     labels:
       - "traefik.enable=true"
  # Routers
       - "traefik.http.routers.catapp.rule=Host(`catapp.localhost`)"
       - "traefik.http.routers.catapp.entrypoints=web"
       - "traefik.http.routers.catapp.middlewares=my-redirect"
       - "traefik.http.routers.catapp-secure.rule=Host(`catapp.localhost`)"
       - "traefik.http.routers.catapp-secure.entrypoints=websecure"
       - "traefik.http.routers.catapp-secure.tls=true"
  #     - "traefik.http.routers.catapp-secure.tls.certresolver=myresolver"
       - "traefik.http.routers.catapp-secure.middlewares=my-compress,my-errorpages,my-ratelimit"
  # Services
  #     - "traefik.http.services.catapp-secure.loadbalancer.server.port=5000"
  # Middleware BasicAuth
       # - "traefik.http.middlewares.test-auth.basicauth.users=traefik:$$apr1$$.zPbdVg8$$LcHeyCZElH.JfxkxxlMPI.,user2:$$apr1$$XDrP1Fb1$$SZqSEjvNYW44vgJgI3iEP0"
       # user1: traefik password: training
       # user2: user2 password: test123
       # Create hash password -> echo $(htpasswd -nb user2 test123) | sed -e s/\\$/\\$\\$/g
  # Compress Middleware
       - "traefik.http.middlewares.my-compress.compress=true"
  # Error Pages Middleware
       - "traefik.http.middlewares.my-errorpages.errors.status=400-599"
       - "traefik.http.middlewares.my-errorpages.errors.service=error"
       - "traefik.http.middlewares.my-errorpages.errors.query=/{status}.html"
  # Rate Limit Middleware
       - "traefik.http.middlewares.my-ratelimit.ratelimit.average=2"
  # Redirect Scheme HTTP -> HTTPS
       - "traefik.http.middlewares.my-redirect.redirectscheme.scheme=https"
       - "traefik.http.middlewares.my-redirect.redirectscheme.permanent=true"

# Add the catapp service
  whoami:
     image: traefik/whoami
     labels:
       - "traefik.enable=true"
  # Routers
       - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"

# Portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9443:9443

  db:
    image: mariadb
    restart: always
    volumes:
     - ./maridb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MariaDB_PASS}
      MARIADB_DATABASE: ${MariaDB_DataBaseName}

  adminer:
    image: adminer
    restart: always
    labels:
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"

  # Error Page service
  error:
    image: guillaumebriday/traefik-custom-error-pages
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.error.rule=Host(`error.localhost`)"
          - "traefik.http.routers.error.service=error"
          - "traefik.http.services.error.loadbalancer.server.port=80"
          # - traefik.frontend.rule=PathPrefixStrip:/wait
          - "traefik.http.routers.error.entrypoints=web"

volumes:
  maridb-data:
  portainer-data:
